### ISSUE TITLE
BUG: FusionHandler sends Exception multiple times

### ISSUE THREAD

**Issue by ru3fu5z** [punktDe/sentry-neos#4]
Since the FusionHandlerAspect, which sends to sentry is triggered after each AbstractRenderingExceptionHandler->handle() the exception is sent 3 times in case going through 3 instances of AbstractRenderingExceptionHandler:
1.   `NodeWrappingHandler->handle()`
2.   `ContentDependentHandler->handle()`
3.   `XmlCommentHandler->handle()`

**Comment by daniellienert** [comment]
Fixed with https://github.com/punktDe/sentry-neos/releases/tag/4.3.0, thanks a lot!
