### ISSUE TITLE
FEATURE: Filter fusion exception for logException rendering option

### ISSUE THREAD

**Issue by ru3fu5z** [punktDe/sentry-neos#5]
It seems unexpected to me that exceptions handled by fusionExceptionHandler are not filtered out. 
Lets make this feature work in Fusion as well:

>## Usage
>Sentry will log all exceptions that have the rendering option logException enabled. This can be enabled or disabled by status code or exception class according to the Flow configuration. 

from punktDe/sentry-flow README

**Comment by daniellienert** [comment]
Fixed with https://github.com/punktDe/sentry-neos/releases/tag/4.3.0, thanks a lot!
